<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IDCAMVERM01-WS" name="Scenario4_Test5" tests="2" failures="2" timestamp="14 Apr 2016 17:01:20 GMT" time="0.316" errors="0">
  <testcase name="verifyscore" time="0.17" classname="com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit">
    <failure type="java.lang.AssertionError" message="expected [3.0] but found [8.81]">
      <![CDATA[java.lang.AssertionError: expected [3.0] but found [8.81]
	at com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit.verifyscore(TestHealthRiskAssessmentSubmit.java:40)
	at com.edifecs.breathe.qa.testcases.RunTests.main(RunTests.java:102)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verifyscore -->
  <testcase name="verifybuttonstatus" time="0.144" classname="com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit">
    <failure type="java.lang.AssertionError" message="Assessment completion status mismatched expected [Not Completed] but found [Completed 04.14.2016]">
      <![CDATA[java.lang.AssertionError: Assessment completion status mismatched expected [Not Completed] but found [Completed 04.14.2016]
	at com.edifecs.breathe.qa.testcases.TestHealthRiskAssessmentSubmit.verifybuttonstatus(TestHealthRiskAssessmentSubmit.java:65)
	at com.edifecs.breathe.qa.testcases.RunTests.main(RunTests.java:102)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verifybuttonstatus -->
</testsuite> <!-- Scenario4_Test5 -->
